package com.airiea.task.model.orm;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;
import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "task-records")
public class TaskRecord {
    @DynamoDBHashKey(attributeName = "task_id")
    @JsonProperty("task_id")
    String taskId;

    @DynamoDBAttribute(attributeName = "knowledge_id")
    @JsonProperty("knowledge_id")
    String knowledgeId;

    @DynamoDBIndexHashKey(attributeName = "entity_id", globalSecondaryIndexName = "entity_id-agent_name")
    @DynamoDBAttribute(attributeName = "entity_id")
    @JsonProperty("entity_id")
    String entityId;

    @DynamoDBIndexRangeKey(attributeName = "agent_name", globalSecondaryIndexName = "entity_id-agent_name")
    @DynamoDBAttribute(attributeName = "agent_name")
    @JsonProperty("agent_name")
    String agentName;

    @DynamoDBAttribute(attributeName = "task_count")
    @JsonProperty("task_count")
    Integer taskCount;

    @DynamoDBAttribute(attributeName = "prompt")
    @JsonProperty("prompt")
    String prompt;

    @DynamoDBAttribute(attributeName = "content")
    @JsonProperty("content")
    String content;

    @DynamoDBAttribute(attributeName = "embedding")
    @JsonProperty("embedding")
    List<Double> embedding;

    @DynamoDBAttribute(attributeName = "status_code")
    @JsonProperty("status_code")
    String statusCode;

    @DynamoDBAttribute(attributeName = "error_code")
    @JsonProperty("error_code")
    String errorCode;

    @DynamoDBAttribute(attributeName = "error_message")
    @JsonProperty("error_message")
    String errorMessage;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    @DynamoDBAttribute(attributeName = "created_date")
    @JsonProperty("created_date")
    Date createdDate;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    @DynamoDBAttribute(attributeName = "updated_date")
    @JsonProperty("updated_date")
    Date updatedDate;
}
